force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Calculate__c.field-meta.xml
<CustomField>
    <fullName>Calculate__c</fullName>
    <formula>IF(
   Total_To_dos__c  = 0,
  0,
  (Number_of_complete_to_dos__c /  Total_To_dos__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Calculate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  Calculate__c = 0,
  &quot;Not Started&quot;,
  IF(
    ROUND(Calculate__c * 100, 0) = 100,
    &quot;Complete&quot;,
    &quot;In Progress&quot;
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Calculate__c.field-meta.xml
<CustomField>
    <fullName>Calculate__c</fullName>
    <formula>IF(
  Total_Milestone__c  = 0,
  0,
 (Total_Complete_Milestone__c / Total_Milestone__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Calculate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
Calculate__c = 0,
&quot;Not Started&quot;,
IF(
ROUND(Calculate__c * 100, 0) = 100,
&quot;Complete&quot;,
&quot;In Progress&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/To_Do_Item__c/To_Do_Item__c.object-meta.xml
<CustomObject>
    <label>To-Do Item</label>
    <nameField>
        <label>To-Do Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Item__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-Do Items</relationshipLabel>
    <relationshipName>To_Do_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectManagerController.cls
public with sharing class ProjectManagerController {

    @AuraEnabled
    public static Id saveProject(Project__c projectRecord) {
        upsert projectRecord;
        return projectRecord.Id;
    }

    @AuraEnabled
    public static List<Milestone__c> saveMilestones(List<Milestone__c> milestoneRecords) {
        upsert milestoneRecords;
        return milestoneRecords;
    }

    @AuraEnabled
    public static List<To_Do_Item__c> saveToDos(List<To_Do_Item__c> toDoRecords) {
        upsert toDoRecords;
        return toDoRecords;
    }

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjectSummary() {
        return [
            SELECT Id, Name, Status__c, Calculate__c,
                (SELECT Id, Name, Due_Date__c, Status__c, Calculate__c,
                    (SELECT Id, Name, Due_Date__c, Status__c FROM To_Do_Items__r)
                FROM Milestones__r)
            FROM Project__c
        ];
    }
}